# Generated by Django 3.1.7 on 2021-04-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210407_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='compte',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='api.compte'),
        ),
    ]
