# Generated by Django 3.1.7 on 2021-04-08 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210408_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='compte',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.compte'),
        ),
    ]
