# Generated by Django 3.1.7 on 2021-04-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210408_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(choices=[('ADMIN', 'Admin.'), ('USER', 'User')], max_length=100)),
            ],
        ),
    ]
