# Generated by Django 3.1.7 on 2021-04-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210412_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donneesraster',
            options={'ordering': ['type']},
        ),
        migrations.AlterModelOptions(
            name='ligne',
            options={'ordering': ['type']},
        ),
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ['type']},
        ),
        migrations.AlterModelOptions(
            name='polygone',
            options={'ordering': ['type']},
        ),
        migrations.AlterModelTable(
            name='point',
            table='points',
        ),
        migrations.AlterModelTable(
            name='polygone',
            table='polygones',
        ),
    ]
