# Generated by Django 3.1.7 on 2021-04-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210413_1245'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ligne',
            table='lignes',
        ),
    ]
