# Generated by Django 3.2 on 2021-04-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210415_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligne',
            name='location',
            field=models.CharField(default=True, max_length=20),
        ),
        # migrations.AddField(
        #     model_name='point',
        #     name='location',
        #     field=models.CharField(default=True, max_length=20),
        # ),
        migrations.AddField(
            model_name='polygone',
            name='location',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
